services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - APP_ADDRESS=:8080
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=eventing
      - DB_SCHEMA=public
    ports:
      - 4001:8080
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=eventing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 10
networks:
  backend:
    driver: bridge
