services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=eventing
      - DB_SCHEMA=public
      - APP_ADDRESS=:8080
    ports:
      - 4001:8080
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=eventing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - backend
networks:
  backend:
    driver: bridge
